In [1]:
# %pip install balldontlie
# %pip install python-dotenv

In [1]:
import os
import pandas as pd
import requests
import pprint

In [3]:
from dotenv import load_dotenv
load_dotenv()

True

In [8]:
API_KEY = os.getenv('AUTH_KEY')

In [4]:
# Import balldontlie API and instantiate
from balldontlie import BalldontlieAPI

In [9]:
api = BalldontlieAPI(api_key= API_KEY)

Get the teams from API

In [10]:
teams = api.nba.teams.list().data;

In [11]:
teams

[NBATeam(id=1, conference='East', division='Southeast', city='Atlanta', name='Hawks', full_name='Atlanta Hawks', abbreviation='ATL'),
 NBATeam(id=2, conference='East', division='Atlantic', city='Boston', name='Celtics', full_name='Boston Celtics', abbreviation='BOS'),
 NBATeam(id=3, conference='East', division='Atlantic', city='Brooklyn', name='Nets', full_name='Brooklyn Nets', abbreviation='BKN'),
 NBATeam(id=4, conference='East', division='Southeast', city='Charlotte', name='Hornets', full_name='Charlotte Hornets', abbreviation='CHA'),
 NBATeam(id=5, conference='East', division='Central', city='Chicago', name='Bulls', full_name='Chicago Bulls', abbreviation='CHI'),
 NBATeam(id=6, conference='East', division='Central', city='Cleveland', name='Cavaliers', full_name='Cleveland Cavaliers', abbreviation='CLE'),
 NBATeam(id=7, conference='West', division='Southwest', city='Dallas', name='Mavericks', full_name='Dallas Mavericks', abbreviation='DAL'),
 NBATeam(id=8, conference='West', division='Northwest', city='Denver', name='Nuggets', full_name='Denver Nuggets', abbreviation='DEN'),
 NBATeam(id=9, conference='East', division='Central', city='Detroit', name='Pistons', full_name='Detroit Pistons', abbreviation='DET'),
 NBATeam(id=10, conference='West', division='Pacific', city='Golden State', name='Warriors', full_name='Golden State Warriors', abbreviation='GSW'),
 NBATeam(id=11, conference='West', division='Southwest', city='Houston', name='Rockets', full_name='Houston Rockets', abbreviation='HOU'),
 NBATeam(id=12, conference='East', division='Central', city='Indiana', name='Pacers', full_name='Indiana Pacers', abbreviation='IND'),
 NBATeam(id=13, conference='West', division='Pacific', city='LA', name='Clippers', full_name='LA Clippers', abbreviation='LAC'),
 NBATeam(id=14, conference='West', division='Pacific', city='Los Angeles', name='Lakers', full_name='Los Angeles Lakers', abbreviation='LAL'),
 NBATeam(id=15, conference='West', division='Southwest', city='Memphis', name='Grizzlies', full_name='Memphis Grizzlies', abbreviation='MEM'),
 NBATeam(id=16, conference='East', division='Southeast', city='Miami', name='Heat', full_name='Miami Heat', abbreviation='MIA'),
 NBATeam(id=17, conference='East', division='Central', city='Milwaukee', name='Bucks', full_name='Milwaukee Bucks', abbreviation='MIL'),
 NBATeam(id=18, conference='West', division='Northwest', city='Minnesota', name='Timberwolves', full_name='Minnesota Timberwolves', abbreviation='MIN'),
 NBATeam(id=19, conference='West', division='Southwest', city='New Orleans', name='Pelicans', full_name='New Orleans Pelicans', abbreviation='NOP'),
 NBATeam(id=20, conference='East', division='Atlantic', city='New York', name='Knicks', full_name='New York Knicks', abbreviation='NYK'),
 NBATeam(id=21, conference='West', division='Northwest', city='Oklahoma City', name='Thunder', full_name='Oklahoma City Thunder', abbreviation='OKC'),
 NBATeam(id=22, conference='East', division='Southeast', city='Orlando', name='Magic', full_name='Orlando Magic', abbreviation='ORL'),
 NBATeam(id=23, conference='East', division='Atlantic', city='Philadelphia', name='76ers', full_name='Philadelphia 76ers', abbreviation='PHI'),
 NBATeam(id=24, conference='West', division='Pacific', city='Phoenix', name='Suns', full_name='Phoenix Suns', abbreviation='PHX'),
 NBATeam(id=25, conference='West', division='Northwest', city='Portland', name='Trail Blazers', full_name='Portland Trail Blazers', abbreviation='POR'),
 NBATeam(id=26, conference='West', division='Pacific', city='Sacramento', name='Kings', full_name='Sacramento Kings', abbreviation='SAC'),
 NBATeam(id=27, conference='West', division='Southwest', city='San Antonio', name='Spurs', full_name='San Antonio Spurs', abbreviation='SAS'),
 NBATeam(id=28, conference='East', division='Atlantic', city='Toronto', name='Raptors', full_name='Toronto Raptors', abbreviation='TOR'),
 NBATeam(id=29, conference='West', division='Northwest', city='Utah', name='Jazz', full_name='Utah Jazz', abbreviation='UTA'),
 NBATeam(id=30, conference='East', division='Southeast', city='Washington', name='Wizards', full_name='Washington Wizards', abbreviation='WAS'),
 NBATeam(id=37, conference='    ', division='', city='', name='Chicago Stags', full_name='Chicago Stags', abbreviation='CHS'),
 NBATeam(id=38, conference='    ', division='', city='', name='St. Louis Bombers', full_name='St. Louis Bombers', abbreviation='BOM'),
 NBATeam(id=39, conference='    ', division='', city='', name='Cleveland Rebels', full_name='Cleveland Rebels', abbreviation='CLR'),
 NBATeam(id=40, conference='    ', division='', city='', name='Detroit Falcons', full_name='Detroit Falcons', abbreviation='DEF'),
 NBATeam(id=41, conference='    ', division='', city='', name='Toronto Huskies', full_name='Toronto Huskies', abbreviation='HUS'),
 NBATeam(id=42, conference='    ', division='', city='', name='Washington Capitols', full_name='Washington Capitols', abbreviation='WAS'),
 NBATeam(id=43, conference='    ', division='', city='', name='Providence Steamrollers', full_name='Providence Steamrollers', abbreviation='PRO'),
 NBATeam(id=44, conference='    ', division='', city='', name='Pittsburgh Ironmen', full_name='Pittsburgh Ironmen', abbreviation='PIT'),
 NBATeam(id=45, conference='    ', division='', city='', name='Baltimore Bullets', full_name='Baltimore Bullets', abbreviation='BAL'),
 NBATeam(id=46, conference='    ', division='', city='', name='Indianapolis Jets', full_name='Indianapolis Jets', abbreviation='JET'),
 NBATeam(id=47, conference='    ', division='', city='', name='Anderson Packers', full_name='Anderson Packers', abbreviation='AND'),
 NBATeam(id=48, conference='    ', division='', city='', name='Waterloo Hawks', full_name='Waterloo Hawks', abbreviation='WAT'),
 NBATeam(id=49, conference='    ', division='', city='', name='Indianapolis Olympians', full_name='Indianapolis Olympians', abbreviation='INO'),
 NBATeam(id=50, conference='    ', division='', city='', name='Denver Nuggets', full_name='Denver Nuggets', abbreviation='DN'),
 NBATeam(id=51, conference='    ', division='', city='', name='Sheboygan Redskins', full_name='Sheboygan Redskins', abbreviation='SHE')]

In [12]:
type(teams)

list

In [13]:
type(teams[0])

balldontlie.nba.models.NBATeam

In [15]:
teams[0].id

1

Getting active players from API

In [16]:
active_players = api.nba.players.list_active(per_page=5)

{'data': [{'id': 3, 'first_name': 'Steven', 'last_name': 'Adams', 'position': 'C', 'height': '6-11', 'weight': '265', 'jersey_number': '12', 'college': 'Pittsburgh', 'country': 'New Zealand', 'draft_year': 2013, 'draft_round': 1, 'draft_number': 12, 'team': {'id': 11, 'conference': 'West', 'division': 'Southwest', 'city': 'Houston', 'name': 'Rockets', 'full_name': 'Houston Rockets', 'abbreviation': 'HOU'}}, {'id': 4, 'first_name': 'Bam', 'last_name': 'Adebayo', 'position': 'C-F', 'height': '6-9', 'weight': '255', 'jersey_number': '13', 'college': 'Kentucky', 'country': 'USA', 'draft_year': 2017, 'draft_round': 1, 'draft_number': 14, 'team': {'id': 16, 'conference': 'East', 'division': 'Southeast', 'city': 'Miami', 'name': 'Heat', 'full_name': 'Miami Heat', 'abbreviation': 'MIA'}}, {'id': 8, 'first_name': 'Grayson', 'last_name': 'Allen', 'position': 'G', 'height': '6-3', 'weight': '198', 'jersey_number': '8', 'college': 'Duke', 'country': 'USA', 'draft_year': 2018, 'draft_round': 1, 'draft_number': 21, 'team': {'id': 24, 'conference': 'West', 'division': 'Pacific', 'city': 'Phoenix', 'name': 'Suns', 'full_name': 'Phoenix Suns', 'abbreviation': 'PHX'}}, {'id': 9, 'first_name': 'Jarrett', 'last_name': 'Allen', 'position': 'C', 'height': '6-9', 'weight': '243', 'jersey_number': '31', 'college': 'Texas', 'country': 'USA', 'draft_year': 2017, 'draft_round': 1, 'draft_number': 22, 'team': {'id': 6, 'conference': 'East', 'division': 'Central', 'city': 'Cleveland', 'name': 'Cavaliers', 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE'}}, {'id': 12, 'first_name': 'Kyle', 'last_name': 'Anderson', 'position': 'F', 'height': '6-8', 'weight': '230', 'jersey_number': '12', 'college': 'UCLA', 'country': 'USA', 'draft_year': 2014, 'draft_round': 1, 'draft_number': 30, 'team': {'id': 18, 'conference': 'West', 'division': 'Northwest', 'city': 'Minnesota', 'name': 'Timberwolves', 'full_name': 'Minnesota Timberwolves', 'abbreviation': 'MIN'}}], 'meta': {'next_cursor': 12, 'per_page': 5}}

In [17]:
active_players.data

[NBAPlayer(id=3, first_name='Steven', last_name='Adams', position='C', height='6-11', weight='265', jersey_number='12', college='Pittsburgh', country='New Zealand', draft_year=2013.0, draft_round=1.0, draft_number=12.0, team=NBATeam(id=11, conference='West', division='Southwest', city='Houston', name='Rockets', full_name='Houston Rockets', abbreviation='HOU'), team_id=None),
 NBAPlayer(id=4, first_name='Bam', last_name='Adebayo', position='C-F', height='6-9', weight='255', jersey_number='13', college='Kentucky', country='USA', draft_year=2017.0, draft_round=1.0, draft_number=14.0, team=NBATeam(id=16, conference='East', division='Southeast', city='Miami', name='Heat', full_name='Miami Heat', abbreviation='MIA'), team_id=None),
 NBAPlayer(id=8, first_name='Grayson', last_name='Allen', position='G', height='6-3', weight='198', jersey_number='8', college='Duke', country='USA', draft_year=2018.0, draft_round=1.0, draft_number=21.0, team=NBATeam(id=24, conference='West', division='Pacific', city='Phoenix', name='Suns', full_name='Phoenix Suns', abbreviation='PHX'), team_id=None),
 NBAPlayer(id=9, first_name='Jarrett', last_name='Allen', position='C', height='6-9', weight='243', jersey_number='31', college='Texas', country='USA', draft_year=2017.0, draft_round=1.0, draft_number=22.0, team=NBATeam(id=6, conference='East', division='Central', city='Cleveland', name='Cavaliers', full_name='Cleveland Cavaliers', abbreviation='CLE'), team_id=None),
 NBAPlayer(id=12, first_name='Kyle', last_name='Anderson', position='F', height='6-8', weight='230', jersey_number='12', college='UCLA', country='USA', draft_year=2014.0, draft_round=1.0, draft_number=30.0, team=NBATeam(id=18, conference='West', division='Northwest', city='Minnesota', name='Timberwolves', full_name='Minnesota Timberwolves', abbreviation='MIN'), team_id=None)]

In [18]:
type(active_players.data)

list

In [19]:
type(active_players.data[0])

balldontlie.nba.models.NBAPlayer

In [41]:
allGames = api.nba.games.list(seasons=['2025'])

{'data': [{'id': 18446819, 'date': '2025-10-21', 'season': 2025, 'status': 'Final', 'period': 6, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 125, 'visitor_team_score': 124, 'datetime': '2025-10-21T23:30:00.000Z', 'home_q1': 27, 'home_q2': 24, 'home_q3': 24, 'home_q4': 29, 'home_ot1': 11, 'home_ot2': 10, 'home_ot3': None, 'home_timeouts_remaining': 1, 'home_in_bonus': True, 'visitor_q1': 30, 'visitor_q2': 27, 'visitor_q3': 22, 'visitor_q4': 25, 'visitor_ot1': 11, 'visitor_ot2': 9, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 21, 'conference': 'West', 'division': 'Northwest', 'city': 'Oklahoma City', 'name': 'Thunder', 'full_name': 'Oklahoma City Thunder', 'abbreviation': 'OKC'}, 'visitor_team': {'id': 11, 'conference': 'West', 'division': 'Southwest', 'city': 'Houston', 'name': 'Rockets', 'full_name': 'Houston Rockets', 'abbreviation': 'HOU'}}, {'id': 18446820, 'date': '2025-10-21', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 109, 'visitor_team_score': 119, 'datetime': '2025-10-22T02:00:00.000Z', 'home_q1': 22, 'home_q2': 32, 'home_q3': 25, 'home_q4': 30, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 1, 'home_in_bonus': True, 'visitor_q1': 28, 'visitor_q2': 27, 'visitor_q3': 35, 'visitor_q4': 29, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 1, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 14, 'conference': 'West', 'division': 'Pacific', 'city': 'Los Angeles', 'name': 'Lakers', 'full_name': 'Los Angeles Lakers', 'abbreviation': 'LAL'}, 'visitor_team': {'id': 10, 'conference': 'West', 'division': 'Pacific', 'city': 'Golden State', 'name': 'Warriors', 'full_name': 'Golden State Warriors', 'abbreviation': 'GSW'}}, {'id': 18446821, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 119, 'visitor_team_score': 111, 'datetime': '2025-10-22T23:00:00.000Z', 'home_q1': 33, 'home_q2': 32, 'home_q3': 22, 'home_q4': 32, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 3, 'home_in_bonus': True, 'visitor_q1': 23, 'visitor_q2': 27, 'visitor_q3': 37, 'visitor_q4': 24, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 1, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 20, 'conference': 'East', 'division': 'Atlantic', 'city': 'New York', 'name': 'Knicks', 'full_name': 'New York Knicks', 'abbreviation': 'NYK'}, 'visitor_team': {'id': 6, 'conference': 'East', 'division': 'Central', 'city': 'Cleveland', 'name': 'Cavaliers', 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE'}}, {'id': 18446822, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 92, 'visitor_team_score': 125, 'datetime': '2025-10-23T01:30:00.000Z', 'home_q1': 29, 'home_q2': 22, 'home_q3': 21, 'home_q4': 20, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 28, 'visitor_q2': 32, 'visitor_q3': 33, 'visitor_q4': 32, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 7, 'conference': 'West', 'division': 'Southwest', 'city': 'Dallas', 'name': 'Mavericks', 'full_name': 'Dallas Mavericks', 'abbreviation': 'DAL'}, 'visitor_team': {'id': 27, 'conference': 'West', 'division': 'Southwest', 'city': 'San Antonio', 'name': 'Spurs', 'full_name': 'San Antonio Spurs', 'abbreviation': 'SAS'}}, {'id': 18446823, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 136, 'visitor_team_score': 117, 'datetime': '2025-10-22T23:00:00.000Z', 'home_q1': 38, 'home_q2': 39, 'home_q3': 34, 'home_q4': 25, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': False, 'visitor_q1': 32, 'visitor_q2': 28, 'visitor_q3': 37, 'visitor_q4': 20, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 4, 'conference': 'East', 'division': 'Southeast', 'city': 'Charlotte', 'name': 'Hornets', 'full_name': 'Charlotte Hornets', 'abbreviation': 'CHA'}, 'visitor_team': {'id': 3, 'conference': 'East', 'division': 'Atlantic', 'city': 'Brooklyn', 'name': 'Nets', 'full_name': 'Brooklyn Nets', 'abbreviation': 'BKN'}}, {'id': 18446824, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 125, 'visitor_team_score': 121, 'datetime': '2025-10-22T23:00:00.000Z', 'home_q1': 38, 'home_q2': 31, 'home_q3': 21, 'home_q4': 35, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 39, 'visitor_q2': 26, 'visitor_q3': 26, 'visitor_q4': 30, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 22, 'conference': 'East', 'division': 'Southeast', 'city': 'Orlando', 'name': 'Magic', 'full_name': 'Orlando Magic', 'abbreviation': 'ORL'}, 'visitor_team': {'id': 16, 'conference': 'East', 'division': 'Southeast', 'city': 'Miami', 'name': 'Heat', 'full_name': 'Miami Heat', 'abbreviation': 'MIA'}}, {'id': 18446825, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 118, 'visitor_team_score': 138, 'datetime': '2025-10-22T23:30:00.000Z', 'home_q1': 34, 'home_q2': 25, 'home_q3': 28, 'home_q4': 31, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 36, 'visitor_q2': 29, 'visitor_q3': 45, 'visitor_q4': 28, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 1, 'conference': 'East', 'division': 'Southeast', 'city': 'Atlanta', 'name': 'Hawks', 'full_name': 'Atlanta Hawks', 'abbreviation': 'ATL'}, 'visitor_team': {'id': 28, 'conference': 'East', 'division': 'Atlantic', 'city': 'Toronto', 'name': 'Raptors', 'full_name': 'Toronto Raptors', 'abbreviation': 'TOR'}}, {'id': 18446826, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 116, 'visitor_team_score': 117, 'datetime': '2025-10-22T23:30:00.000Z', 'home_q1': 28, 'home_q2': 23, 'home_q3': 35, 'home_q4': 30, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 26, 'visitor_q2': 31, 'visitor_q3': 18, 'visitor_q4': 42, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 2, 'conference': 'East', 'division': 'Atlantic', 'city': 'Boston', 'name': 'Celtics', 'full_name': 'Boston Celtics', 'abbreviation': 'BOS'}, 'visitor_team': {'id': 23, 'conference': 'East', 'division': 'Atlantic', 'city': 'Philadelphia', 'name': '76ers', 'full_name': 'Philadelphia 76ers', 'abbreviation': 'PHI'}}, {'id': 18446827, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 115, 'visitor_team_score': 111, 'datetime': '2025-10-23T00:00:00.000Z', 'home_q1': 35, 'home_q2': 29, 'home_q3': 30, 'home_q4': 21, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 1, 'home_in_bonus': True, 'visitor_q1': 19, 'visitor_q2': 30, 'visitor_q3': 30, 'visitor_q4': 32, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 5, 'conference': 'East', 'division': 'Central', 'city': 'Chicago', 'name': 'Bulls', 'full_name': 'Chicago Bulls', 'abbreviation': 'CHI'}, 'visitor_team': {'id': 9, 'conference': 'East', 'division': 'Central', 'city': 'Detroit', 'name': 'Pistons', 'full_name': 'Detroit Pistons', 'abbreviation': 'DET'}}, {'id': 18446828, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 128, 'visitor_team_score': 122, 'datetime': '2025-10-23T00:00:00.000Z', 'home_q1': 27, 'home_q2': 29, 'home_q3': 41, 'home_q4': 31, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 30, 'visitor_q2': 37, 'visitor_q3': 22, 'visitor_q4': 33, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 15, 'conference': 'West', 'division': 'Southwest', 'city': 'Memphis', 'name': 'Grizzlies', 'full_name': 'Memphis Grizzlies', 'abbreviation': 'MEM'}, 'visitor_team': {'id': 19, 'conference': 'West', 'division': 'Southwest', 'city': 'New Orleans', 'name': 'Pelicans', 'full_name': 'New Orleans Pelicans', 'abbreviation': 'NOP'}}, {'id': 18446829, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 133, 'visitor_team_score': 120, 'datetime': '2025-10-23T00:00:00.000Z', 'home_q1': 40, 'home_q2': 32, 'home_q3': 29, 'home_q4': 32, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 23, 'visitor_q2': 30, 'visitor_q3': 37, 'visitor_q4': 30, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 1, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 17, 'conference': 'East', 'division': 'Central', 'city': 'Milwaukee', 'name': 'Bucks', 'full_name': 'Milwaukee Bucks', 'abbreviation': 'MIL'}, 'visitor_team': {'id': 30, 'conference': 'East', 'division': 'Southeast', 'city': 'Washington', 'name': 'Wizards', 'full_name': 'Washington Wizards', 'abbreviation': 'WAS'}}, {'id': 18446830, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 129, 'visitor_team_score': 108, 'datetime': '2025-10-23T01:00:00.000Z', 'home_q1': 43, 'home_q2': 35, 'home_q3': 30, 'home_q4': 21, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 19, 'visitor_q2': 28, 'visitor_q3': 33, 'visitor_q4': 28, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 29, 'conference': 'West', 'division': 'Northwest', 'city': 'Utah', 'name': 'Jazz', 'full_name': 'Utah Jazz', 'abbreviation': 'UTA'}, 'visitor_team': {'id': 13, 'conference': 'West', 'division': 'Pacific', 'city': 'LA', 'name': 'Clippers', 'full_name': 'LA Clippers', 'abbreviation': 'LAC'}}, {'id': 18446831, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 120, 'visitor_team_score': 116, 'datetime': '2025-10-23T02:00:00.000Z', 'home_q1': 19, 'home_q2': 35, 'home_q3': 36, 'home_q4': 30, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 29, 'visitor_q2': 42, 'visitor_q3': 21, 'visitor_q4': 24, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 24, 'conference': 'West', 'division': 'Pacific', 'city': 'Phoenix', 'name': 'Suns', 'full_name': 'Phoenix Suns', 'abbreviation': 'PHX'}, 'visitor_team': {'id': 26, 'conference': 'West', 'division': 'Pacific', 'city': 'Sacramento', 'name': 'Kings', 'full_name': 'Sacramento Kings', 'abbreviation': 'SAC'}}, {'id': 18446832, 'date': '2025-10-22', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 114, 'visitor_team_score': 118, 'datetime': '2025-10-23T02:00:00.000Z', 'home_q1': 35, 'home_q2': 26, 'home_q3': 34, 'home_q4': 19, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 33, 'visitor_q2': 24, 'visitor_q3': 31, 'visitor_q4': 30, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 25, 'conference': 'West', 'division': 'Northwest', 'city': 'Portland', 'name': 'Trail Blazers', 'full_name': 'Portland Trail Blazers', 'abbreviation': 'POR'}, 'visitor_team': {'id': 18, 'conference': 'West', 'division': 'Northwest', 'city': 'Minnesota', 'name': 'Timberwolves', 'full_name': 'Minnesota Timberwolves', 'abbreviation': 'MIN'}}, {'id': 18446833, 'date': '2025-10-23', 'season': 2025, 'status': 'Final', 'period': 6, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 135, 'visitor_team_score': 141, 'datetime': '2025-10-23T23:30:00.000Z', 'home_q1': 25, 'home_q2': 22, 'home_q3': 31, 'home_q4': 35, 'home_ot1': 11, 'home_ot2': 11, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': False, 'visitor_q1': 22, 'visitor_q2': 32, 'visitor_q3': 27, 'visitor_q4': 32, 'visitor_ot1': 11, 'visitor_ot2': 17, 'visitor_ot3': None, 'visitor_timeouts_remaining': 1, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 12, 'conference': 'East', 'division': 'Central', 'city': 'Indiana', 'name': 'Pacers', 'full_name': 'Indiana Pacers', 'abbreviation': 'IND'}, 'visitor_team': {'id': 21, 'conference': 'West', 'division': 'Northwest', 'city': 'Oklahoma City', 'name': 'Thunder', 'full_name': 'Oklahoma City Thunder', 'abbreviation': 'OKC'}}, {'id': 18446834, 'date': '2025-10-23', 'season': 2025, 'status': 'Final', 'period': 5, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 137, 'visitor_team_score': 131, 'datetime': '2025-10-24T02:00:00.000Z', 'home_q1': 27, 'home_q2': 34, 'home_q3': 33, 'home_q4': 26, 'home_ot1': 17, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 31, 'visitor_q2': 39, 'visitor_q3': 24, 'visitor_q4': 26, 'visitor_ot1': 11, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 10, 'conference': 'West', 'division': 'Pacific', 'city': 'Golden State', 'name': 'Warriors', 'full_name': 'Golden State Warriors', 'abbreviation': 'GSW'}, 'visitor_team': {'id': 8, 'conference': 'West', 'division': 'Northwest', 'city': 'Denver', 'name': 'Nuggets', 'full_name': 'Denver Nuggets', 'abbreviation': 'DEN'}}, {'id': 18446835, 'date': '2025-10-24', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 105, 'visitor_team_score': 95, 'datetime': '2025-10-24T23:30:00.000Z', 'home_q1': 22, 'home_q2': 42, 'home_q3': 18, 'home_q4': 23, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 1, 'home_in_bonus': True, 'visitor_q1': 30, 'visitor_q2': 14, 'visitor_q3': 21, 'visitor_q4': 30, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 20, 'conference': 'East', 'division': 'Atlantic', 'city': 'New York', 'name': 'Knicks', 'full_name': 'New York Knicks', 'abbreviation': 'NYK'}, 'visitor_team': {'id': 2, 'conference': 'East', 'division': 'Atlantic', 'city': 'Boston', 'name': 'Celtics', 'full_name': 'Boston Celtics', 'abbreviation': 'BOS'}}, {'id': 18446836, 'date': '2025-10-24', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 128, 'visitor_team_score': 110, 'datetime': '2025-10-25T02:00:00.000Z', 'home_q1': 36, 'home_q2': 32, 'home_q3': 40, 'home_q4': 20, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 2, 'home_in_bonus': True, 'visitor_q1': 40, 'visitor_q2': 23, 'visitor_q3': 31, 'visitor_q4': 16, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': False, 'ist_stage': None, 'home_team': {'id': 14, 'conference': 'West', 'division': 'Pacific', 'city': 'Los Angeles', 'name': 'Lakers', 'full_name': 'Los Angeles Lakers', 'abbreviation': 'LAL'}, 'visitor_team': {'id': 18, 'conference': 'West', 'division': 'Northwest', 'city': 'Minnesota', 'name': 'Timberwolves', 'full_name': 'Minnesota Timberwolves', 'abbreviation': 'MIN'}}, {'id': 18446837, 'date': '2025-10-24', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 107, 'visitor_team_score': 111, 'datetime': '2025-10-24T23:00:00.000Z', 'home_q1': 24, 'home_q2': 37, 'home_q3': 25, 'home_q4': 21, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 25, 'visitor_q2': 26, 'visitor_q3': 27, 'visitor_q4': 33, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 0, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 22, 'conference': 'East', 'division': 'Southeast', 'city': 'Orlando', 'name': 'Magic', 'full_name': 'Orlando Magic', 'abbreviation': 'ORL'}, 'visitor_team': {'id': 1, 'conference': 'East', 'division': 'Southeast', 'city': 'Atlanta', 'name': 'Hawks', 'full_name': 'Atlanta Hawks', 'abbreviation': 'ATL'}}, {'id': 18446838, 'date': '2025-10-24', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 124, 'visitor_team_score': 131, 'datetime': '2025-10-24T23:30:00.000Z', 'home_q1': 23, 'home_q2': 28, 'home_q3': 35, 'home_q4': 38, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': False, 'visitor_q1': 34, 'visitor_q2': 29, 'visitor_q3': 45, 'visitor_q4': 23, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 1, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 3, 'conference': 'East', 'division': 'Atlantic', 'city': 'Brooklyn', 'name': 'Nets', 'full_name': 'Brooklyn Nets', 'abbreviation': 'BKN'}, 'visitor_team': {'id': 6, 'conference': 'East', 'division': 'Central', 'city': 'Cleveland', 'name': 'Cavaliers', 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE'}}, {'id': 18446839, 'date': '2025-10-24', 'season': 2025, 'status': 'Final', 'period': 4, 'time': 'Final', 'postseason': False, 'postponed': False, 'home_team_score': 116, 'visitor_team_score': 122, 'datetime': '2025-10-24T22:30:00.000Z', 'home_q1': 19, 'home_q2': 35, 'home_q3': 32, 'home_q4': 30, 'home_ot1': None, 'home_ot2': None, 'home_ot3': None, 'home_timeouts_remaining': 0, 'home_in_bonus': True, 'visitor_q1': 27, 'visitor_q2': 25, 'visitor_q3': 34, 'visitor_q4': 36, 'visitor_ot1': None, 'visitor_ot2': None, 'visitor_ot3': None, 'visitor_timeouts_remaining': 2, 'visitor_in_bonus': True, 'ist_stage': None, 'home_team': {'id': 28, 'conference': 'East', 'division': 'Atlantic', 'city': 'Toronto', 'name': 'Raptors', 'full_name': 'Toronto Raptors', 'abbreviation': 'TOR'}, 'visitor_team': {'id': 17, 'conference': 'East', 'division': 'Central', 'city': 'Milwaukee', 'name': 'Bucks', 'full_name': 'Milwaukee Bucks', 'abbreviation': 'MIL'}}, {'id': 18446840, 'd

In [42]:
allGames = allGames.data

In [43]:
allGames

[NBAGame(id=18446819, date='2025-10-21', season=2025, status='Final', period=6.0, time='Final', postseason=False, home_team_score=125.0, visitor_team_score=124.0, home_team=NBATeam(id=21, conference='West', division='Northwest', city='Oklahoma City', name='Thunder', full_name='Oklahoma City Thunder', abbreviation='OKC'), home_team_id=None, visitor_team=NBATeam(id=11, conference='West', division='Southwest', city='Houston', name='Rockets', full_name='Houston Rockets', abbreviation='HOU'), visitor_team_id=None),
 NBAGame(id=18446820, date='2025-10-21', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=109.0, visitor_team_score=119.0, home_team=NBATeam(id=14, conference='West', division='Pacific', city='Los Angeles', name='Lakers', full_name='Los Angeles Lakers', abbreviation='LAL'), home_team_id=None, visitor_team=NBATeam(id=10, conference='West', division='Pacific', city='Golden State', name='Warriors', full_name='Golden State Warriors', abbreviation='GSW'), visitor_team_id=None),
 NBAGame(id=18446821, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=119.0, visitor_team_score=111.0, home_team=NBATeam(id=20, conference='East', division='Atlantic', city='New York', name='Knicks', full_name='New York Knicks', abbreviation='NYK'), home_team_id=None, visitor_team=NBATeam(id=6, conference='East', division='Central', city='Cleveland', name='Cavaliers', full_name='Cleveland Cavaliers', abbreviation='CLE'), visitor_team_id=None),
 NBAGame(id=18446822, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=92.0, visitor_team_score=125.0, home_team=NBATeam(id=7, conference='West', division='Southwest', city='Dallas', name='Mavericks', full_name='Dallas Mavericks', abbreviation='DAL'), home_team_id=None, visitor_team=NBATeam(id=27, conference='West', division='Southwest', city='San Antonio', name='Spurs', full_name='San Antonio Spurs', abbreviation='SAS'), visitor_team_id=None),
 NBAGame(id=18446823, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=136.0, visitor_team_score=117.0, home_team=NBATeam(id=4, conference='East', division='Southeast', city='Charlotte', name='Hornets', full_name='Charlotte Hornets', abbreviation='CHA'), home_team_id=None, visitor_team=NBATeam(id=3, conference='East', division='Atlantic', city='Brooklyn', name='Nets', full_name='Brooklyn Nets', abbreviation='BKN'), visitor_team_id=None),
 NBAGame(id=18446824, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=125.0, visitor_team_score=121.0, home_team=NBATeam(id=22, conference='East', division='Southeast', city='Orlando', name='Magic', full_name='Orlando Magic', abbreviation='ORL'), home_team_id=None, visitor_team=NBATeam(id=16, conference='East', division='Southeast', city='Miami', name='Heat', full_name='Miami Heat', abbreviation='MIA'), visitor_team_id=None),
 NBAGame(id=18446825, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=118.0, visitor_team_score=138.0, home_team=NBATeam(id=1, conference='East', division='Southeast', city='Atlanta', name='Hawks', full_name='Atlanta Hawks', abbreviation='ATL'), home_team_id=None, visitor_team=NBATeam(id=28, conference='East', division='Atlantic', city='Toronto', name='Raptors', full_name='Toronto Raptors', abbreviation='TOR'), visitor_team_id=None),
 NBAGame(id=18446826, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=116.0, visitor_team_score=117.0, home_team=NBATeam(id=2, conference='East', division='Atlantic', city='Boston', name='Celtics', full_name='Boston Celtics', abbreviation='BOS'), home_team_id=None, visitor_team=NBATeam(id=23, conference='East', division='Atlantic', city='Philadelphia', name='76ers', full_name='Philadelphia 76ers', abbreviation='PHI'), visitor_team_id=None),
 NBAGame(id=18446827, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=115.0, visitor_team_score=111.0, home_team=NBATeam(id=5, conference='East', division='Central', city='Chicago', name='Bulls', full_name='Chicago Bulls', abbreviation='CHI'), home_team_id=None, visitor_team=NBATeam(id=9, conference='East', division='Central', city='Detroit', name='Pistons', full_name='Detroit Pistons', abbreviation='DET'), visitor_team_id=None),
 NBAGame(id=18446828, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=128.0, visitor_team_score=122.0, home_team=NBATeam(id=15, conference='West', division='Southwest', city='Memphis', name='Grizzlies', full_name='Memphis Grizzlies', abbreviation='MEM'), home_team_id=None, visitor_team=NBATeam(id=19, conference='West', division='Southwest', city='New Orleans', name='Pelicans', full_name='New Orleans Pelicans', abbreviation='NOP'), visitor_team_id=None),
 NBAGame(id=18446829, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=133.0, visitor_team_score=120.0, home_team=NBATeam(id=17, conference='East', division='Central', city='Milwaukee', name='Bucks', full_name='Milwaukee Bucks', abbreviation='MIL'), home_team_id=None, visitor_team=NBATeam(id=30, conference='East', division='Southeast', city='Washington', name='Wizards', full_name='Washington Wizards', abbreviation='WAS'), visitor_team_id=None),
 NBAGame(id=18446830, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=129.0, visitor_team_score=108.0, home_team=NBATeam(id=29, conference='West', division='Northwest', city='Utah', name='Jazz', full_name='Utah Jazz', abbreviation='UTA'), home_team_id=None, visitor_team=NBATeam(id=13, conference='West', division='Pacific', city='LA', name='Clippers', full_name='LA Clippers', abbreviation='LAC'), visitor_team_id=None),
 NBAGame(id=18446831, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=120.0, visitor_team_score=116.0, home_team=NBATeam(id=24, conference='West', division='Pacific', city='Phoenix', name='Suns', full_name='Phoenix Suns', abbreviation='PHX'), home_team_id=None, visitor_team=NBATeam(id=26, conference='West', division='Pacific', city='Sacramento', name='Kings', full_name='Sacramento Kings', abbreviation='SAC'), visitor_team_id=None),
 NBAGame(id=18446832, date='2025-10-22', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=114.0, visitor_team_score=118.0, home_team=NBATeam(id=25, conference='West', division='Northwest', city='Portland', name='Trail Blazers', full_name='Portland Trail Blazers', abbreviation='POR'), home_team_id=None, visitor_team=NBATeam(id=18, conference='West', division='Northwest', city='Minnesota', name='Timberwolves', full_name='Minnesota Timberwolves', abbreviation='MIN'), visitor_team_id=None),
 NBAGame(id=18446833, date='2025-10-23', season=2025, status='Final', period=6.0, time='Final', postseason=False, home_team_score=135.0, visitor_team_score=141.0, home_team=NBATeam(id=12, conference='East', division='Central', city='Indiana', name='Pacers', full_name='Indiana Pacers', abbreviation='IND'), home_team_id=None, visitor_team=NBATeam(id=21, conference='West', division='Northwest', city='Oklahoma City', name='Thunder', full_name='Oklahoma City Thunder', abbreviation='OKC'), visitor_team_id=None),
 NBAGame(id=18446834, date='2025-10-23', season=2025, status='Final', period=5.0, time='Final', postseason=False, home_team_score=137.0, visitor_team_score=131.0, home_team=NBATeam(id=10, conference='West', division='Pacific', city='Golden State', name='Warriors', full_name='Golden State Warriors', abbreviation='GSW'), home_team_id=None, visitor_team=NBATeam(id=8, conference='West', division='Northwest', city='Denver', name='Nuggets', full_name='Denver Nuggets', abbreviation='DEN'), visitor_team_id=None),
 NBAGame(id=18446835, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=105.0, visitor_team_score=95.0, home_team=NBATeam(id=20, conference='East', division='Atlantic', city='New York', name='Knicks', full_name='New York Knicks', abbreviation='NYK'), home_team_id=None, visitor_team=NBATeam(id=2, conference='East', division='Atlantic', city='Boston', name='Celtics', full_name='Boston Celtics', abbreviation='BOS'), visitor_team_id=None),
 NBAGame(id=18446836, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=128.0, visitor_team_score=110.0, home_team=NBATeam(id=14, conference='West', division='Pacific', city='Los Angeles', name='Lakers', full_name='Los Angeles Lakers', abbreviation='LAL'), home_team_id=None, visitor_team=NBATeam(id=18, conference='West', division='Northwest', city='Minnesota', name='Timberwolves', full_name='Minnesota Timberwolves', abbreviation='MIN'), visitor_team_id=None),
 NBAGame(id=18446837, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=107.0, visitor_team_score=111.0, home_team=NBATeam(id=22, conference='East', division='Southeast', city='Orlando', name='Magic', full_name='Orlando Magic', abbreviation='ORL'), home_team_id=None, visitor_team=NBATeam(id=1, conference='East', division='Southeast', city='Atlanta', name='Hawks', full_name='Atlanta Hawks', abbreviation='ATL'), visitor_team_id=None),
 NBAGame(id=18446838, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=124.0, visitor_team_score=131.0, home_team=NBATeam(id=3, conference='East', division='Atlantic', city='Brooklyn', name='Nets', full_name='Brooklyn Nets', abbreviation='BKN'), home_team_id=None, visitor_team=NBATeam(id=6, conference='East', division='Central', city='Cleveland', name='Cavaliers', full_name='Cleveland Cavaliers', abbreviation='CLE'), visitor_team_id=None),
 NBAGame(id=18446839, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=116.0, visitor_team_score=122.0, home_team=NBATeam(id=28, conference='East', division='Atlantic', city='Toronto', name='Raptors', full_name='Toronto Raptors', abbreviation='TOR'), home_team_id=None, visitor_team=NBATeam(id=17, conference='East', division='Central', city='Milwaukee', name='Bucks', full_name='Milwaukee Bucks', abbreviation='MIL'), visitor_team_id=None),
 NBAGame(id=18446840, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=111.0, visitor_team_score=115.0, home_team=NBATeam(id=11, conference='West', division='Southwest', city='Houston', name='Rockets', full_name='Houston Rockets', abbreviation='HOU'), home_team_id=None, visitor_team=NBATeam(id=9, conference='East', division='Central', city='Detroit', name='Pistons', full_name='Detroit Pistons', abbreviation='DET'), visitor_team_id=None),
 NBAGame(id=18446841, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=114.0, visitor_team_score=146.0, home_team=NBATeam(id=15, conference='West', division='Southwest', city='Memphis', name='Grizzlies', full_name='Memphis Grizzlies', abbreviation='MEM'), home_team_id=None, visitor_team=NBATeam(id=16, conference='East', division='Southeast', city='Miami', name='Heat', full_name='Miami Heat', abbreviation='MIA'), visitor_team_id=None),
 NBAGame(id=18446842, date='2025-10-24', season=2025, status='Final', period=5.0, time='Final', postseason=False, home_team_score=116.0, visitor_team_score=120.0, home_team=NBATeam(id=19, conference='West', division='Southwest', city='New Orleans', name='Pelicans', full_name='New Orleans Pelicans', abbreviation='NOP'), home_team_id=None, visitor_team=NBATeam(id=27, conference='West', division='Southwest', city='San Antonio', name='Spurs', full_name='San Antonio Spurs', abbreviation='SAS'), visitor_team_id=None),
 NBAGame(id=18446843, date='2025-10-24', season=2025, status='Final', period=4.0, time='Final', postseason=False, home_team_score=107.0, visitor_team_score=117.0, home_team=NBATeam(id=7, conference='West', division='Southwest', city='Dallas', name='Mavericks', full_name='Dallas Mavericks', abbreviation='DAL'), home_team_id=None, visitor_team=NBATeam(id=30, conference='East', division='Southeast', city='Washington', name='Wizards', full_name='Washington Wizards', abbreviation='WAS'), visitor_team_id=None)]

In [44]:
allGamesSimple = []

Needed to map game data for DF and SQL

In [45]:
for game in allGames:
    allGamesSimple.append({
        'game_id': game.id,
        'date': game.date,
        'season': game.season,
        "status": game.status,
        "period": game.period,
        "time": game.time,
        "postseason": game.postseason,
        "home_team_score": game.home_team_score,
        "visitor_team_score": game.visitor_team_score,
        "home_team_id": game.home_team.id,
        "home_team_name": game.home_team.name,
        "home_team_abb": game.home_team.abbreviation,
        "visitor_team_id": game.visitor_team.id,
        "visitor_team_name": game.visitor_team.name,
        "visitor_team_abb": game.visitor_team.abbreviation
    })

In [46]:
gamesDF = pd.DataFrame(allGamesSimple)

In [47]:
gamesDF

,game_id,date,season,status,period,time,postseason,home_team_score,visitor_team_score,home_team_id,home_team_name,home_team_abb,visitor_team_id,visitor_team_name,visitor_team_abb
0,18446819,2025-10-21,2025,Final,6.0,Final,False,125.0,124.0,21,Thunder,OKC,11,Rockets,HOU
1,18446820,2025-10-21,2025,Final,4.0,Final,False,109.0,119.0,14,Lakers,LAL,10,Warriors,GSW
2,18446821,2025-10-22,2025,Final,4.0,Final,False,119.0,111.0,20,Knicks,NYK,6,Cavaliers,CLE
3,18446822,2025-10-22,2025,Final,4.0,Final,False,92.0,125.0,7,Mavericks,DAL,27,Spurs,SAS
4,18446823,2025-10-22,2025,Final,4.0,Final,False,136.0,117.0,4,Hornets,CHA,3,Nets,BKN
5,18446824,2025-10-22,2025,Final,4.0,Final,False,125.0,121.0,22,Magic,ORL,16,Heat,MIA
6,18446825,2025-10-22,2025,Final,4.0,Final,False,118.0,138.0,1,Hawks,ATL,28,Raptors,TOR
7,18446826,2025-10-22,2025,Final,4.0,Final,False,116.0,117.0,2,Celtics,BOS,23,76ers,PHI
8,18446827,2025-10-22,2025,Final,4.0,Final,False,115.0,111.0,5,Bulls,CHI,9,Pistons,DET
9,18446828,2025-10-22,2025,Final,4.0,Final,False,128.0,122.0,15,Grizzlies,MEM,19,Pelicans,NOP
10,18446829,2025-10-22,2025,Final,4.0,Final,False,133.0,120.0,17,Bucks,MIL,30,Wizards,WAS
11,18446830,2025-10-22,2025,Final,4.0,Final,False,129.0,108.0,29,Jazz,UTA,13,Clippers,LAC
12,18446831,2025-10-22,2025,Final,4.0,Final,False,120.0,116.0,24,Suns,PHX,26,Kings,SAC
13,18446832,2025-10-22,2025,Final,4.0,Final,False,114.0,118.0,25,Trail Blazers,POR,18,Timberwolves,MIN
14,18446833,2025-10-23,2025,Final,6.0,Final,False,135.0,141.0,12,Pacers,IND,21,Thunder,OKC
15,18446834,2025-10-23,2025,Final,5.0,Final,False,137.0,131.0,10,Warriors,GSW,8,Nuggets,DEN
16,18446835,2025-10-24,2025,Final,4.0,Final,False,105.0,95.0,20,Knicks,NYK,2,Celtics,BOS
17,18446836,2025-10-24,2025,Final,4.0,Final,False,128.0,110.0,14,Lakers,LAL,18,Timberwolves,MIN
18,18446837,2025-10-24,2025,Final,4.0,Final,False,107.0,111.0,22,Magic,ORL,1,Hawks,ATL
19,18446838,2025-10-24,2025,Final,4.0,Final,False,124.0,131.0,3,Nets,BKN,6,Cavaliers,CLE
20,18446839,2025-10-24,2025,Final,4.0,Final,False,116.0,122.0,28,Raptors,TOR,17,Bucks,MIL
21,18446840,2025-10-24,2025,Final,4.0,Final,False,111.0,115.0,11,Rockets,HOU,9,Pistons,DET
22,18446841,2025-10-24,2025,Final,4.0,Final,False,114.0,146.0,15,Grizzlies,MEM,16,Heat,MIA
23,18446842,2025-10-24,2025,Final,5.0,Final,False,116.0,120.0,19,Pelicans,NOP,27,Spurs,SAS
24,18446843,2025-10-24,2025,Final,4.0,Final,False,107.0,117.0,7,Mavericks,DAL,30,Wizards,WAS

In [48]:
test_game = api.nba.games.get(18446819)

In [50]:
test_game.data

NBAGame(id=18446819, date='2025-10-21', season=2025, status='Final', period=6.0, time='Final', postseason=False, home_team_score=125.0, visitor_team_score=124.0, home_team=NBATeam(id=21, conference='West', division='Northwest', city='Oklahoma City', name='Thunder', full_name='Oklahoma City Thunder', abbreviation='OKC'), home_team_id=None, visitor_team=NBATeam(id=11, conference='West', division='Southwest', city='Houston', name='Rockets', full_name='Houston Rockets', abbreviation='HOU'), visitor_team_id=None)

Testing to see if each game data can be pulled using the game id field! -> SUCCESS!!

In [66]:
# allStats = api.nba.stats.list(game_ids=[18446819])

In [52]:
allStats = allStats.data

In [82]:
# allStats

this is CLUTCH!!!

In [54]:
data_as_dicts = [item.model_dump() for item in allStats]

In [83]:
# data_as_dicts

In [56]:
statsDF = pd.json_normalize(data_as_dicts)

In [57]:
statsDF.head()

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,game.status,game.period,game.time,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team,game.home_team_id,game.visitor_team,game.visitor_team_id
0,20748292.0,45,2.0,12.0,0.167,0.0,8.0,0.000,2.0,2.0,...,Final,6.0,Final,False,125.0,124.0,None,21.0,None,11.0
1,20748293.0,38,11.0,17.0,0.647,2.0,5.0,0.400,4.0,4.0,...,Final,6.0,Final,False,125.0,124.0,None,21.0,None,11.0
2,20748294.0,37,2.0,5.0,0.400,0.0,1.0,0.000,2.0,2.0,...,Final,6.0,Final,False,125.0,124.0,None,21.0,None,11.0
3,20748295.0,42,5.0,10.0,0.500,3.0,8.0,0.375,1.0,2.0,...,Final,6.0,Final,False,125.0,124.0,None,21.0,None,11.0
4,20748296.0,47,12.0,26.0,0.462,1.0,9.0,0.111,10.0,14.0,...,Final,6.0,Final,False,125.0,124.0,None,21.0,None,11.0

In [76]:
statsDF[['id', 'player.id', 'pts']]

            id   player.id   pts
0   20748292.0      666541   6.0
1   20748293.0    38017685  28.0
2   20748294.0         201   6.0
3   20748295.0    56677833  14.0
4   20748296.0         175  35.0
5   20748297.0  1057392335   0.0
6   20748298.0          89   8.0
7   20748299.0    38017716   0.0
8   20748300.0  1028037477  16.0
9   20748301.0    17896078  10.0
10  20748302.0    38017706   2.0
11  20748303.0  1057849685   0.0
12  20748304.0  1028218679   0.0
13  20748305.0     3547272   0.0
14  20748306.0  1057274983   0.0
15  20748307.0  1028028932   0.0
16  20748308.0    38017703   0.0
17  20748309.0         480   0.0
18  20748310.0    38017684  16.0
19  20748311.0    17896062  39.0
20  20748312.0           3   4.0
21  20748313.0         140  23.0
22  20748314.0    56677825  18.0
23  20748315.0          83   4.0
24  20748316.0    38017707   0.0

In [81]:
statsDF.columns.tolist()

['id',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'turnover',
 'pf',
 'pts',
 'player.id',
 'player.first_name',
 'player.last_name',
 'player.position',
 'player.height',
 'player.weight',
 'player.jersey_number',
 'player.college',
 'player.country',
 'player.draft_year',
 'player.draft_round',
 'player.draft_number',
 'player.team',
 'player.team_id',
 'team.id',
 'team.conference',
 'team.division',
 'team.city',
 'team.name',
 'team.full_name',
 'team.abbreviation',
 'game.id',
 'game.date',
 'game.season',
 'game.status',
 'game.period',
 'game.time',
 'game.postseason',
 'game.home_team_score',
 'game.visitor_team_score',
 'game.home_team',
 'game.home_team_id',
 'game.visitor_team',
 'game.visitor_team_id']

In [85]:
statsDF.drop(columns=[
 'player.position',
 'player.height',
 'player.weight',
 'player.jersey_number',
 'player.college',
 'player.country',
 'player.draft_year',
 'player.draft_round',
 'player.draft_number',
 'player.team',
 'team.id',
 'team.conference',
 'team.division',
 'team.city',
 'team.name',
 'team.full_name',
 'team.abbreviation',
 'game.status',
 'game.period',
 'game.time',
 'game.home_team',
 'game.visitor_team'])

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
0,20748292.0,45,2.0,12.0,0.167,0.0,8.0,0.000,2.0,2.0,...,Dort,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
1,20748293.0,38,11.0,17.0,0.647,2.0,5.0,0.400,4.0,4.0,...,Holmgren,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
2,20748294.0,37,2.0,5.0,0.400,0.0,1.0,0.000,2.0,2.0,...,Hartenstein,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
3,20748295.0,42,5.0,10.0,0.500,3.0,8.0,0.375,1.0,2.0,...,Wallace,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
4,20748296.0,47,12.0,26.0,0.462,1.0,9.0,0.111,10.0,14.0,...,Gilgeous-Alexander,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
5,20748297.0,2,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,Barnhizer,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
6,20748298.0,30,3.0,9.0,0.333,2.0,6.0,0.333,0.0,0.0,...,Caruso,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
7,20748299.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Dieng,17.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
8,20748300.0,15,6.0,12.0,0.500,3.0,6.0,0.500,1.0,1.0,...,Mitchell,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
9,20748301.0,21,4.0,8.0,0.500,2.0,5.0,0.400,0.0,0.0,...,Wiggins,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
10,20748302.0,13,1.0,5.0,0.200,0.0,4.0,0.000,0.0,0.0,...,Williams,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
11,20748303.0,0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,Youngblood,25.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
12,20748304.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Carlson,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
13,20748305.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Joe,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
14,20748306.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Sorber,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
15,20748307.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Topic,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
16,20748308.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Williams,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
17,20748309.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Williams,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
18,20748310.0,42,7.0,15.0,0.467,2.0,6.0,0.333,0.0,0.0,...,Smith Jr.,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
19,20748311.0,49,12.0,24.0,0.500,5.0,8.0,0.625,10.0,11.0,...,Sengun,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
20,20748312.0,37,1.0,4.0,0.250,0.0,0.0,NaN,2.0,2.0,...,Adams,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
21,20748313.0,47,9.0,16.0,0.563,0.0,4.0,0.000,5.0,6.0,...,Durant,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
22,20748314.0,39,8.0,17.0,0.471,0.0,7.0,0.000,2.0,2.0,...,Thompson,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
23,20748315.0,8,1.0,1.0,1.000,0.0,0.0,NaN,2.0,2.0,...,Capela,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
24,20748316.0,00,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,...,Davison,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0

In [87]:
for index, row in statsDF.iterrows():
    print(row['player.first_name'],row['player.last_name'])

Luguentz Dort
Chet Holmgren
Isaiah Hartenstein
Cason Wallace
Shai Gilgeous-Alexander
Brooks Barnhizer
Alex Caruso
Ousmane Dieng
Ajay Mitchell
Aaron Wiggins
Jaylin Williams
Chris Youngblood
Branden Carlson
Isaiah Joe
Thomas Sorber
Nikola Topic
Jalen Williams
Kenrich Williams
Jabari Smith Jr.
Alperen Sengun
Steven Adams
Kevin Durant
Amen Thompson
Clint Capela
JD Davison

In [88]:
type(statsDF)

pandas.DataFrame

In [92]:
gamestats = pd.read_csv('game_stats.csv', index_col=0)

In [93]:
gamestats.head()

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
0,20748292.0,45,2.0,12.0,0.167,0.0,8.0,0.000,2.0,2.0,...,Dort,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
1,20748293.0,38,11.0,17.0,0.647,2.0,5.0,0.400,4.0,4.0,...,Holmgren,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
2,20748294.0,37,2.0,5.0,0.400,0.0,1.0,0.000,2.0,2.0,...,Hartenstein,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
3,20748295.0,42,5.0,10.0,0.500,3.0,8.0,0.375,1.0,2.0,...,Wallace,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
4,20748296.0,47,12.0,26.0,0.462,1.0,9.0,0.111,10.0,14.0,...,Gilgeous-Alexander,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0

In [103]:
gamesDF['game_id'] = gamesDF['game_id'].astype('int64')

In [119]:
gamesDF.sort_values('game_id', ascending=False)

,game_id,date,season,status,period,time,postseason,home_team_score,visitor_team_score,home_team_id,home_team_name,home_team_abb,visitor_team_id,visitor_team_name,visitor_team_abb
24,18446843,2025-10-24,2025,Final,4.0,Final,False,107.0,117.0,7,Mavericks,DAL,30,Wizards,WAS
23,18446842,2025-10-24,2025,Final,5.0,Final,False,116.0,120.0,19,Pelicans,NOP,27,Spurs,SAS
22,18446841,2025-10-24,2025,Final,4.0,Final,False,114.0,146.0,15,Grizzlies,MEM,16,Heat,MIA
21,18446840,2025-10-24,2025,Final,4.0,Final,False,111.0,115.0,11,Rockets,HOU,9,Pistons,DET
20,18446839,2025-10-24,2025,Final,4.0,Final,False,116.0,122.0,28,Raptors,TOR,17,Bucks,MIL
19,18446838,2025-10-24,2025,Final,4.0,Final,False,124.0,131.0,3,Nets,BKN,6,Cavaliers,CLE
18,18446837,2025-10-24,2025,Final,4.0,Final,False,107.0,111.0,22,Magic,ORL,1,Hawks,ATL
17,18446836,2025-10-24,2025,Final,4.0,Final,False,128.0,110.0,14,Lakers,LAL,18,Timberwolves,MIN
16,18446835,2025-10-24,2025,Final,4.0,Final,False,105.0,95.0,20,Knicks,NYK,2,Celtics,BOS
15,18446834,2025-10-23,2025,Final,5.0,Final,False,137.0,131.0,10,Warriors,GSW,8,Nuggets,DEN
14,18446833,2025-10-23,2025,Final,6.0,Final,False,135.0,141.0,12,Pacers,IND,21,Thunder,OKC
13,18446832,2025-10-22,2025,Final,4.0,Final,False,114.0,118.0,25,Trail Blazers,POR,18,Timberwolves,MIN
12,18446831,2025-10-22,2025,Final,4.0,Final,False,120.0,116.0,24,Suns,PHX,26,Kings,SAC
11,18446830,2025-10-22,2025,Final,4.0,Final,False,129.0,108.0,29,Jazz,UTA,13,Clippers,LAC
10,18446829,2025-10-22,2025,Final,4.0,Final,False,133.0,120.0,17,Bucks,MIL,30,Wizards,WAS
9,18446828,2025-10-22,2025,Final,4.0,Final,False,128.0,122.0,15,Grizzlies,MEM,19,Pelicans,NOP
8,18446827,2025-10-22,2025,Final,4.0,Final,False,115.0,111.0,5,Bulls,CHI,9,Pistons,DET
7,18446826,2025-10-22,2025,Final,4.0,Final,False,116.0,117.0,2,Celtics,BOS,23,76ers,PHI
6,18446825,2025-10-22,2025,Final,4.0,Final,False,118.0,138.0,1,Hawks,ATL,28,Raptors,TOR
5,18446824,2025-10-22,2025,Final,4.0,Final,False,125.0,121.0,22,Magic,ORL,16,Heat,MIA
4,18446823,2025-10-22,2025,Final,4.0,Final,False,136.0,117.0,4,Hornets,CHA,3,Nets,BKN
3,18446822,2025-10-22,2025,Final,4.0,Final,False,92.0,125.0,7,Mavericks,DAL,27,Spurs,SAS
2,18446821,2025-10-22,2025,Final,4.0,Final,False,119.0,111.0,20,Knicks,NYK,6,Cavaliers,CLE
1,18446820,2025-10-21,2025,Final,4.0,Final,False,109.0,119.0,14,Lakers,LAL,10,Warriors,GSW
0,18446819,2025-10-21,2025,Final,6.0,Final,False,125.0,124.0,21,Thunder,OKC,11,Rockets,HOU

In [122]:
gamesDF = pd.read_csv('games.csv', index_col=0)

In [129]:
gamesDF.game_id[gamesDF.game_id > 18447743].count()

np.int64(368)

In [130]:
gameStats = pd.read_csv('game_stats.csv', index_col=0)

In [131]:
gameStats.head()

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
0,20748292.0,45,2.0,12.0,0.167,0.0,8.0,0.000,2.0,2.0,...,Dort,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
1,20748293.0,38,11.0,17.0,0.647,2.0,5.0,0.400,4.0,4.0,...,Holmgren,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
2,20748294.0,37,2.0,5.0,0.400,0.0,1.0,0.000,2.0,2.0,...,Hartenstein,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
3,20748295.0,42,5.0,10.0,0.500,3.0,8.0,0.375,1.0,2.0,...,Wallace,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
4,20748296.0,47,12.0,26.0,0.462,1.0,9.0,0.111,10.0,14.0,...,Gilgeous-Alexander,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0

In [132]:
gameStats.sort_values('game.id', ascending=False)

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
13565,22909818.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,Shamet,20.0,20377171,2025-12-16,2025,False,124.0,113.0,20.0,27.0
13570,22909823.0,32,5.0,13.0,0.384615,2.0,6.0,0.333333,4.0,6.0,...,Fox,27.0,20377171,2025-12-16,2025,False,124.0,113.0,20.0,27.0
13567,22909820.0,23,4.0,9.0,0.444444,0.0,4.0,0.000000,3.0,3.0,...,Barnes,27.0,20377171,2025-12-16,2025,False,124.0,113.0,20.0,27.0
13566,22909819.0,33,4.0,14.0,0.285714,2.0,7.0,0.285714,2.0,2.0,...,Vassell,27.0,20377171,2025-12-16,2025,False,124.0,113.0,20.0,27.0
13564,22909817.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,McBride,20.0,20377171,2025-12-16,2025,False,124.0,113.0,20.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,20748316.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,Davison,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
23,20748315.0,8,1.0,1.0,1.000000,0.0,0.0,NaN,2.0,2.0,...,Capela,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
22,20748314.0,39,8.0,17.0,0.471000,0.0,7.0,0.000000,2.0,2.0,...,Thompson,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
21,20748313.0,47,9.0,16.0,0.563000,0.0,4.0,0.000000,5.0,6.0,...,Durant,11.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0
0,20748292.0,45,2.0,12.0,0.167000,0.0,8.0,0.000000,2.0,2.0,...,Dort,21.0,18446819,2025-10-21,2025,False,125.0,124.0,21.0,11.0

In [2]:
gamesListDf = pd.read_csv('games.csv')

In [3]:
gamesListDf.head()

,Unnamed: 0,game_id,date,season,status,period,time,postseason,home_team_score,visitor_team_score,home_team_id,home_team_name,home_team_abb,visitor_team_id,visitor_team_name,visitor_team_abb
0,0,18446819,2025-10-21,2025,Final,6.0,Final,False,125.0,124.0,21,Thunder,OKC,11,Rockets,HOU
1,1,18446820,2025-10-21,2025,Final,4.0,Final,False,109.0,119.0,14,Lakers,LAL,10,Warriors,GSW
2,2,18446821,2025-10-22,2025,Final,4.0,Final,False,119.0,111.0,20,Knicks,NYK,6,Cavaliers,CLE
3,3,18446822,2025-10-22,2025,Final,4.0,Final,False,92.0,125.0,7,Mavericks,DAL,27,Spurs,SAS
4,4,18446823,2025-10-22,2025,Final,4.0,Final,False,136.0,117.0,4,Hornets,CHA,3,Nets,BKN

In [4]:
gamesListDf.set_index(gamesListDf.columns[0])

,game_id,date,season,status,period,time,postseason,home_team_score,visitor_team_score,home_team_id,home_team_name,home_team_abb,visitor_team_id,visitor_team_name,visitor_team_abb
Unnamed: 0,,,,,,,,,,,,,,,
0,18446819,2025-10-21,2025,Final,6.0,Final,False,125.0,124.0,21,Thunder,OKC,11,Rockets,HOU
1,18446820,2025-10-21,2025,Final,4.0,Final,False,109.0,119.0,14,Lakers,LAL,10,Warriors,GSW
2,18446821,2025-10-22,2025,Final,4.0,Final,False,119.0,111.0,20,Knicks,NYK,6,Cavaliers,CLE
3,18446822,2025-10-22,2025,Final,4.0,Final,False,92.0,125.0,7,Mavericks,DAL,27,Spurs,SAS
4,18446823,2025-10-22,2025,Final,4.0,Final,False,136.0,117.0,4,Hornets,CHA,3,Nets,BKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,21682743,2026-05-02,2025,2026-05-02T04:00:00Z,0.0,NaN,True,0.0,0.0,2,Celtics,BOS,23,76ers,PHI
1289,21682000,2026-05-03,2025,2026-05-03T04:00:00Z,0.0,NaN,True,0.0,0.0,6,Cavaliers,CLE,28,Raptors,TOR
1290,21682001,2026-05-03,2025,2026-05-03T04:00:00Z,0.0,NaN,True,0.0,0.0,14,Lakers,LAL,11,Rockets,HOU
1291,21684819,2026-05-03,2025,2026-05-03T04:00:00Z,0.0,NaN,True,0.0,0.0,9,Pistons,DET,22,Magic,ORL
1292,21684925,2026-05-03,2025,2026-05-03T04:00:00Z,0.0,NaN,True,0.0,0.0,21,Thunder,OKC,24,Suns,PHX

In [5]:
gameStatsDf = pd.read_csv('game_stats.csv')

In [7]:
gameStatsDf.set_index(gameStatsDf.columns[0])

,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,36922149.0,35,10.0,21.0,0.476191,5.0,10.0,0.500000,0.0,0.0,...,Bey,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0
1,36922150.0,28,6.0,8.0,0.750000,0.0,0.0,0.000000,2.0,2.0,...,Williamson,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0
2,36922151.0,26,2.0,4.0,0.500000,1.0,2.0,0.500000,2.0,2.0,...,Jones,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0
3,36922152.0,40,7.0,17.0,0.411765,4.0,12.0,0.333333,5.0,6.0,...,Murphy III,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0
4,36922153.0,30,7.0,12.0,0.583333,3.0,7.0,0.428571,0.0,0.0,...,Murray,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7733,41311290.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,Highsmith,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0
7734,41311291.0,19,2.0,3.0,0.667000,0.0,1.0,0.000000,0.0,0.0,...,Maluach,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0
7735,41311292.0,34,4.0,5.0,0.800000,4.0,5.0,0.800000,4.0,4.0,...,O'Neale,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0
7736,41311293.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,Goodwin,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0
7737,41311294.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,Williams,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0

In [8]:
gameStatsDf.columns

Index(['Unnamed: 0', 'id', 'min', 'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a',
       'fg3_pct', 'ftm', 'fta', 'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl',
       'blk', 'turnover', 'pf', 'pts', 'player.id', 'player.first_name',
       'player.last_name', 'player.team_id', 'game.id', 'game.date',
       'game.season', 'game.postseason', 'game.home_team_score',
       'game.visitor_team_score', 'game.home_team_id', 'game.visitor_team_id'],
      dtype='str')

In [10]:
gameStatsDf.sort_values('game.date', ascending=False)

,Unnamed: 0,id,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,...,player.last_name,player.team_id,game.id,game.date,game.season,game.postseason,game.home_team_score,game.visitor_team_score,game.home_team_id,game.visitor_team_id
7737,7737,41311294.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,Williams,24.0,21684886,2026-04-22,2025,True,120.0,107.0,21.0,24.0
7707,7707,41256964.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,Isaac,22.0,21684786,2026-04-22,2025,True,98.0,83.0,9.0,22.0
7705,7705,41256962.0,3,2.0,2.0,1.000000,2.0,2.0,1.000000,0.0,...,Richardson,22.0,21684786,2026-04-22,2025,True,98.0,83.0,9.0,22.0
7704,7704,41256961.0,3,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,Penda,22.0,21684786,2026-04-22,2025,True,98.0,83.0,9.0,22.0
7703,7703,41256960.0,3,0.0,2.0,0.000000,0.0,2.0,0.000000,0.0,...,Howard,22.0,21684786,2026-04-22,2025,True,98.0,83.0,9.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,76,37018291.0,42,11.0,19.0,0.578947,0.0,1.0,0.000000,4.0,...,Thompson,11.0,18447825,2026-03-18,2025,False,116.0,124.0,11.0,14.0
77,77,37018292.0,3,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,Capela,11.0,18447825,2026-03-18,2025,False,116.0,124.0,11.0,14.0
78,78,37018293.0,0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,Crawford,11.0,18447825,2026-03-18,2025,False,116.0,124.0,11.0,14.0
79,79,37018294.0,9,1.0,3.0,0.333333,1.0,3.0,0.333333,0.0,...,Finney-Smith,11.0,18447825,2026-03-18,2025,False,116.0,124.0,11.0,14.0
0,0,36922149.0,35,10.0,21.0,0.476191,5.0,10.0,0.500000,0.0,...,Bey,19.0,18447823,2026-03-18,2025,False,124.0,109.0,19.0,13.0