In [1]:
# %pip install nba_api

In [2]:
import pandas as pd

In [3]:
from nba_api.stats.static import teams

In [4]:
type(teams)

module

Trying to find all methods associated to the module

In [5]:
dir(teams)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_find_team_by_abbreviation',
 '_find_team_name_by_id',
 '_find_teams',
 '_find_teams_by_championship_year',
 '_find_teams_by_year_founded',
 '_get_team_dict',
 '_get_teams',
 'find_team_by_abbreviation',
 'find_team_name_by_id',
 'find_teams_by_championship_year',
 'find_teams_by_city',
 'find_teams_by_full_name',
 'find_teams_by_nickname',
 'find_teams_by_state',
 'find_teams_by_year_founded',
 'find_wnba_team_by_abbreviation',
 'find_wnba_team_name_by_id',
 'find_wnba_teams_by_championship_year',
 'find_wnba_teams_by_city',
 'find_wnba_teams_by_full_name',
 'find_wnba_teams_by_nickname',
 'find_wnba_teams_by_state',
 'find_wnba_teams_by_year_founded',
 'get_teams',
 'get_wnba_teams',
 're',
 'team_index_abbreviation',
 'team_index_championship_year',
 'team_index_city',
 'team_index_full_name',
 'team_index_id',
 'team_index_nickname',
 'team_index_state',
 'team_index_year_founded',
 'teams',
 'wnba_teams']

In [6]:
nba_teams = teams.get_teams()

Number of teams in the NBA

In [7]:
nba_teams[0]
len(nba_teams)

30

Teams and their team id's, going to need this later to query all players from each team

In [8]:
for team in nba_teams:
    print(team['id'], team['abbreviation'])

1610612737 ATL
1610612738 BOS
1610612739 CLE
1610612740 NOP
1610612741 CHI
1610612742 DAL
1610612743 DEN
1610612744 GSW
1610612745 HOU
1610612746 LAC
1610612747 LAL
1610612748 MIA
1610612749 MIL
1610612750 MIN
1610612751 BKN
1610612752 NYK
1610612753 ORL
1610612754 IND
1610612755 PHI
1610612756 PHX
1610612757 POR
1610612758 SAC
1610612759 SAS
1610612760 OKC
1610612761 TOR
1610612762 UTA
1610612763 MEM
1610612764 WAS
1610612765 DET
1610612766 CHA

Finding players - searching my team id

In [9]:
from nba_api.stats.endpoints import playerindex

In [10]:
players = playerindex.PlayerIndex(team_id_nullable='1610612757')

In [11]:
por_players = players.get_data_frames()[0]

In [12]:
por_players.head()

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020.0,1.0,9.0,1.0,2020,2025,24.2,6.9,6.7,Season
1,1641739,Camara,Toumani,toumani-camara,blazers,1610612757,Portland,Trail Blazers,POR,33,...,2023.0,2.0,52.0,1.0,2023,2025,13.4,5.1,2.5,Season
2,1631321,Cissoko,Sidy,sidy-cissoko,blazers,1610612757,Portland,Trail Blazers,POR,91,...,2023.0,2.0,44.0,1.0,2023,2025,5.1,2.2,1.5,Season
3,1642270,Clingan,Donovan,donovan-clingan,blazers,1610612757,Portland,Trail Blazers,POR,23,...,2024.0,1.0,7.0,1.0,2024,2025,12.1,11.6,2.1,Season
4,203924,Grant,Jerami,jerami-grant,blazers,1610612757,Portland,Trail Blazers,POR,9,...,2014.0,2.0,39.0,1.0,2014,2025,18.6,3.5,2.1,Season

In [13]:
por_players.sort_values('TO_YEAR', ascending=False)

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020.0,1.0,9.0,1.0,2020,2025,24.2,6.9,6.7,Season
1,1641739,Camara,Toumani,toumani-camara,blazers,1610612757,Portland,Trail Blazers,POR,33,...,2023.0,2.0,52.0,1.0,2023,2025,13.4,5.1,2.5,Season
16,1642905,Hansen,Yang,yang-hansen,blazers,1610612757,Portland,Trail Blazers,POR,16,...,2025.0,1.0,16.0,1.0,2025,2025,2.2,1.5,0.5,Season
15,1629057,Williams III,Robert,robert-williams-iii,blazers,1610612757,Portland,Trail Blazers,POR,35,...,2018.0,1.0,27.0,1.0,2018,2025,6.7,7.0,1.0,Season
14,1631104,Wesley,Blake,blake-wesley,blazers,1610612757,Portland,Trail Blazers,POR,1,...,2022.0,1.0,25.0,1.0,2022,2025,4.8,1.3,2.0,Season
13,1629680,Thybulle,Matisse,matisse-thybulle,blazers,1610612757,Portland,Trail Blazers,POR,4,...,2019.0,1.0,20.0,1.0,2019,2025,5.8,2.0,0.9,Season
12,1631101,Sharpe,Shaedon,shaedon-sharpe,blazers,1610612757,Portland,Trail Blazers,POR,17,...,2022.0,1.0,7.0,1.0,2022,2025,20.8,4.3,2.6,Season
11,1631200,Murray,Kris,kris-murray,blazers,1610612757,Portland,Trail Blazers,POR,24,...,2023.0,1.0,23.0,1.0,2023,2025,5.8,3.6,1.4,Season
10,1631126,Love,Caleb,caleb-love,blazers,1610612757,Portland,Trail Blazers,POR,2,...,NaN,NaN,NaN,1.0,2025,2025,10.4,2.3,2.5,Season
9,203081,Lillard,Damian,damian-lillard,blazers,1610612757,Portland,Trail Blazers,POR,0,...,2012.0,1.0,6.0,1.0,2012,2025,NaN,NaN,NaN,Season
8,1630249,Krejčí,Vít,vít-krejčí,blazers,1610612757,Portland,Trail Blazers,POR,27,...,2020.0,2.0,37.0,1.0,2021,2025,8.5,2.3,1.5,Season
7,1643257,Kent,Jayson,jayson-kent,blazers,1610612757,Portland,Trail Blazers,POR,NaN,...,NaN,NaN,NaN,1.0,2025,2025,2.0,1.0,0.0,Season
6,201950,Holiday,Jrue,jrue-holiday,blazers,1610612757,Portland,Trail Blazers,POR,5,...,2009.0,1.0,17.0,1.0,2009,2025,16.3,4.6,6.1,Season
5,1630703,Henderson,Scoot,scoot-henderson,blazers,1610612757,Portland,Trail Blazers,POR,00,...,2023.0,1.0,3.0,1.0,2023,2025,14.2,2.7,3.7,Season
4,203924,Grant,Jerami,jerami-grant,blazers,1610612757,Portland,Trail Blazers,POR,9,...,2014.0,2.0,39.0,1.0,2014,2025,18.6,3.5,2.1,Season
3,1642270,Clingan,Donovan,donovan-clingan,blazers,1610612757,Portland,Trail Blazers,POR,23,...,2024.0,1.0,7.0,1.0,2024,2025,12.1,11.6,2.1,Season
2,1631321,Cissoko,Sidy,sidy-cissoko,blazers,1610612757,Portland,Trail Blazers,POR,91,...,2023.0,2.0,44.0,1.0,2023,2025,5.1,2.2,1.5,Season
17,1642959,Youngblood,Chris,chris-youngblood,blazers,1610612757,Portland,Trail Blazers,POR,3,...,NaN,NaN,NaN,1.0,2025,2025,2.1,0.8,0.4,Season

In [14]:
draft_2020 = playerindex.PlayerIndex(team_id_nullable='1610612757', draft_year_nullable='2020')

In [15]:
draft_2020.get_data_frames()[0]

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020,1,9,1.0,2020,2025,24.2,6.9,6.7,Season
1,1630249,Krejčí,Vít,vít-krejčí,blazers,1610612757,Portland,Trail Blazers,POR,27,...,2020,2,37,1.0,2021,2025,8.5,2.3,1.5,Season

NOTE: not all columns are made equal, need to check using dtypes and potentially convert

In [16]:
por_players.DRAFT_YEAR = por_players.DRAFT_YEAR.astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [ ]:
por_players.dtypes

Trying to find player stats

In [ ]:
from nba_api.stats.endpoints import playerdashboardbylastngames

In [ ]:
player_stats = playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id='1629057', last_n_games=20)

In [ ]:
player_stats.get_data_frames()[0]

In [ ]:
dir(players)

Finding players and player ids from players directory

In [ ]:
from nba_api.stats.static import players

In [ ]:
dir(players)

In [ ]:
players.find_players_by_first_name('lebron')

Trying to query for one player to retrieve stats

In [ ]:
from nba_api.stats.endpoints import playerdashboardbyteamperformance

In [ ]:
james = playerdashboardbyteamperformance.PlayerDashboardByTeamPerformance(player_id='2544')

In [ ]:
frames = james.get_data_frames()

In [ ]:
frames[1]

Lots of this data does not make sense (to me)

In [ ]:
frames[0]

In [ ]:
from nba_api.stats.endpoints import playercareerstats

In [ ]:
player_stats = playercareerstats.PlayerCareerStats(player_id='2544')

In [ ]:
player_stats.get_json()

In [ ]:
stats = player_stats.get_data_frames()[4]

In [ ]:
stats

NOTE: this is the API to use, to retrieve game data for each player

In [ ]:
from nba_api.stats.endpoints import playergamelog

In [ ]:
current_gamelog = playergamelog.PlayerGameLog(player_id='2544')

In [ ]:
logs = current_gamelog.get_data_frames()[0]

In [ ]:
logs.head()

In [ ]:
logs.dtypes